import MainNav from '../components/mainNav'
import './../css/globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <MainNav/>
        {children}</body>
    </html>
  )
}
